import { randomBytes } from 'node:crypto';
import { aplicarCarta, DEFINICOES_CARTAS, LIMITE_MAO, movimentosRevive, normalizarCartas } from '../cards/cards.js';
import { aplicarNoTabuleiro, estaEmXeque, iniciarTabuleiro, movimentosLegais, oposta, VALORES_PECAS } from '../game/game.js';
import type { CartaId, Casa, Cor, Jogador, Papel, Peca, Sala, TipoPeca } from '../game/types.js'; import type { RoomRepository } from '../persistence/repository.js';
export interface StatePublisher { publish(room:Sala):void;publishRooms():void; }
const token=()=>randomBytes(12).toString('hex');export const normalizarCodigo=(s:unknown)=>String(s??'').trim().toUpperCase();const copyPeca=(p:Peca)=>({...p,modificadores:[...p.modificadores]});const ctx=(s:Sala)=>({direitosRoque:s.direitosRoque,enPassant:s.enPassant});
function jogador(data:Partial<Jogador>={}):Jogador{const c=normalizarCartas(data);return{token:data.token||token(),mao:c.mao,baralho:c.baralho,cemiterio:(data.cemiterio??[]).map(copyPeca),cartaUsadaNesteTurno:!!data.cartaUsadaNesteTurno,conectado:false};}function comprar(s:Sala,cor:Cor){const j=s.jogadores[cor];if(j.mao.length<LIMITE_MAO&&j.baralho.length){const id=j.baralho.pop()!;j.mao.push({...DEFINICOES_CARTAS[id]});}}
function chave(s:Sala){return JSON.stringify({t:s.turno,b:s.tabuleiro.map(r=>r.map(p=>p&&[p.tipo,p.cor,p.modificadores])),r:s.direitosRoque,e:s.enPassant,maos:{b:s.jogadores.branco.mao.map(x=>x.id),p:s.jogadores.preto.mao.map(x=>x.id)}});}
function materialInsuficiente(s:Sala){if(s.jogadores.branco.mao.length||s.jogadores.preto.mao.length||s.jogadores.branco.baralho.length||s.jogadores.preto.baralho.length)return false;const extras:{p:Peca;l:number;c:number}[]=[];for(let l=0;l<8;l++)for(let c=0;c<8;c++){const p=s.tabuleiro[l][c];if(p&&p.tipo!=='rei')extras.push({p,l,c});}if(!extras.length)return true;if(extras.length===1&&['bispo','cavalo'].includes(extras[0].p.tipo))return true;return extras.length>0&&extras.every(x=>x.p.tipo==='bispo')&&extras.every(x=>(x.l+x.c)%2===(extras[0].l+extras[0].c)%2);}
function possuiLance(s:Sala,cor:Cor){for(let l=0;l<8;l++)for(let c=0;c<8;c++)if(movimentosLegais({linha:l,coluna:c},cor,s.tabuleiro,ctx(s)).length)return true;return false;}
function atualizarResultado(s:Sala){if(s.resultado.estado!=='em_andamento'&&s.resultado.estado!=='xeque')return;const legal=possuiLance(s,s.turno),check=estaEmXeque(s.turno,s.tabuleiro);if(!legal){s.resultado=check?{estado:'xeque_mate',vencedor:oposta(s.turno)}:{estado:'afogamento',vencedor:null};return;}const n=s.historicoPosicoes[chave(s)]??0;if(s.meioLances>=150)s.resultado={estado:'empate_75_lances',vencedor:null};else if(n>=5||n>=3)s.resultado={estado:'empate_repeticao',vencedor:null};else if(s.meioLances>=100)s.resultado={estado:'empate_50_lances',vencedor:null};else if(materialInsuficiente(s))s.resultado={estado:'empate_material_insuficiente',vencedor:null};else s.resultado={estado:check?'xeque':'em_andamento',vencedor:null};}
export function criarSala(codigo:string,saved?:Partial<Sala>):Sala{const s:Sala={codigo:normalizarCodigo(codigo),tabuleiro:saved?.tabuleiro??iniciarTabuleiro(),jogadores:{branco:jogador(saved?.jogadores?.branco),preto:jogador(saved?.jogadores?.preto)},turno:saved?.turno??'branco',placar:{branco:saved?.placar?.branco??0,preto:saved?.placar?.preto??0},direitosRoque:saved?.direitosRoque??{branco:{curto:true,longo:true},preto:{curto:true,longo:true}},enPassant:saved?.enPassant??null,meioLances:saved?.meioLances??0,historicoPosicoes:saved?.historicoPosicoes??{},resultado:saved?.resultado??{estado:'em_andamento',vencedor:null}};for(const c of ['branco','preto']as Cor[])while(s.jogadores[c].mao.length<3&&s.jogadores[c].baralho.length)comprar(s,c);s.historicoPosicoes[chave(s)]??=1;atualizarResultado(s);return s;}
export class RoomService{private rooms=new Map<string,Sala>();constructor(private repo:RoomRepository,private publisher:StatePublisher){}async load(){for(const state of await this.repo.loadAll()){const r=criarSala(state.codigo,state);this.rooms.set(r.codigo,r);}}get(code:unknown){return this.rooms.get(normalizarCodigo(code));}list(){return[...this.rooms.values()];}create(requested?:unknown){let code=normalizarCodigo(requested);if(!code){do{code=randomBytes(3).toString('hex').toUpperCase();}while(this.rooms.has(code));}if(this.rooms.has(code))throw new Error('Já existe uma sala com esse código.');const r=criarSala(code);this.rooms.set(code,r);this.changed(r);return r;}
role(room:Sala,supplied?:unknown,spectator=false):Papel{const t=String(supplied??'').trim();if(!spectator&&t===room.jogadores.branco.token)return'branco';if(!spectator&&t===room.jogadores.preto.token)return'preto';if(!spectator&&!room.jogadores.branco.conectado)return'branco';if(!spectator&&!room.jogadores.preto.conectado)return'preto';return'espectador';}connect(room:Sala,role:Papel,supplied?:unknown){if(role!=='espectador'){room.jogadores[role].conectado=true;const t=String(supplied??'').trim();if(t)room.jogadores[role].token=t;}this.changed(room);}disconnect(room:Sala,role:Papel){if(role!=='espectador'){room.jogadores[role].conectado=false;this.changed(room);}}
moves(room:Sala,role:Papel,origem:Casa,cartaId?:CartaId){if(!this.ativa(room)||role==='espectador'||role!==room.turno)return{movimentos:[],opcoesReviviveis:[]};const p=room.tabuleiro[origem?.linha]?.[origem?.coluna];if(!p||p.cor!==room.turno)return{movimentos:[],opcoesReviviveis:[]};if(cartaId==='reviver_aliado')return{movimentos:movimentosRevive(room,origem).filter(destino=>this.cartaLegal(room,role,{cartaId,origem,destino})),opcoesReviviveis:room.jogadores[role].cemiterio.map((p,i)=>({indice:i,tipo:p.tipo,cor:p.cor}))};return{movimentos:movimentosLegais(origem,role,room.tabuleiro,ctx(room)),opcoesReviviveis:[]};}
requiresPromotion(room:Sala,origem:Casa,destino:Casa){const p=room.tabuleiro[origem?.linha]?.[origem?.coluna];return p?.tipo==='peao'&&(destino.linha===0||destino.linha===7);}move(room:Sala,role:Papel,origem:Casa,destino:Casa,promocao?:TipoPeca){if(!this.ativa(room)||role==='espectador'||role!==room.turno||!movimentosLegais(origem,role,room.tabuleiro,ctx(room)).some(x=>x.linha===destino.linha&&x.coluna===destino.coluna))return false;const p=room.tabuleiro[origem.linha][origem.coluna]!;if(this.requiresPromotion(room,origem,destino)&&!['rainha','torre','bispo','cavalo'].includes(promocao??''))return false;const normal=room.tabuleiro[destino.linha][destino.coluna],ep=p.tipo==='peao'&&room.enPassant?.linha===destino.linha&&room.enPassant?.coluna===destino.coluna&&!normal?room.tabuleiro[origem.linha][destino.coluna]:null,hit=normal??ep;if(hit){room.placar[p.cor]+=VALORES_PECAS[hit.tipo];room.jogadores[hit.cor].cemiterio.push(copyPeca(hit));}room.tabuleiro=aplicarNoTabuleiro(room.tabuleiro,origem,destino,ctx(room));const moved=room.tabuleiro[destino.linha][destino.coluna]!;if(promocao)moved.tipo=promocao;moved.modificadores=moved.modificadores.filter(x=>x!=='marcha_lateral'&&x!=='salto_cavaleiro');this.direitos(room,p,origem,destino,hit);room.enPassant=p.tipo==='peao'&&Math.abs(destino.linha-origem.linha)===2?{linha:(origem.linha+destino.linha)/2,coluna:origem.coluna}:null;room.meioLances=p.tipo==='peao'||!!hit?0:room.meioLances+1;room.turno=oposta(room.turno);room.jogadores[room.turno].cartaUsadaNesteTurno=false;comprar(room,room.turno);this.registrar(room);this.changed(room);return true;}
card(room:Sala,role:Papel,data:{cartaId:CartaId;origem:Casa;destino?:Casa;indiceRevivido?:number}){if(!this.ativa(room)||role==='espectador'||!this.cartaLegal(room,role,data))return false;const ok=aplicarCarta(room,role,data);if(ok){this.registrar(room);this.changed(room);}return ok;}private ativa(s:Sala){return s.resultado.estado==='em_andamento'||s.resultado.estado==='xeque';}private cartaLegal(room:Sala,role:Cor,data:{cartaId:CartaId;origem:Casa;destino?:Casa;indiceRevivido?:number}){const copy=structuredClone(room)as Sala;return aplicarCarta(copy,role,data)&&!estaEmXeque(role,copy.tabuleiro);}private direitos(s:Sala,p:Peca,o:Casa,d:Casa,hit:Peca|null){const home=p.cor==='branco'?7:0;if(p.tipo==='rei')s.direitosRoque[p.cor]={curto:false,longo:false};if(p.tipo==='torre'&&o.linha===home){if(o.coluna===0)s.direitosRoque[p.cor].longo=false;if(o.coluna===7)s.direitosRoque[p.cor].curto=false;}if(hit?.tipo==='torre'){const h=hit.cor==='branco'?7:0;if(d.linha===h&&d.coluna===0)s.direitosRoque[hit.cor].longo=false;if(d.linha===h&&d.coluna===7)s.direitosRoque[hit.cor].curto=false;}}private registrar(s:Sala){const k=chave(s);s.historicoPosicoes[k]=(s.historicoPosicoes[k]??0)+1;atualizarResultado(s);}private changed(room:Sala){void this.repo.save(room).catch(console.error);this.publisher.publish(room);this.publisher.publishRooms();}}
