import type { Casa, Cor, DireitosRoque, Peca, Tabuleiro, TipoPeca } from './types.js';
export const VALORES_PECAS: Record<TipoPeca, number> = { peao: 1, cavalo: 3, bispo: 3, torre: 5, rainha: 9, rei: 0 };
export const criarPeca=(tipo:TipoPeca,cor:Cor):Peca=>({tipo,cor,modificadores:[]}); export const oposta=(c:Cor):Cor=>c==='branco'?'preto':'branco'; export const casaValida=({linha,coluna}:Casa)=>linha>=0&&linha<8&&coluna>=0&&coluna<8;
export const copiarTabuleiro=(t:Tabuleiro):Tabuleiro=>t.map(l=>l.map(p=>p&&({...p,modificadores:[...p.modificadores]})));
export function iniciarTabuleiro():Tabuleiro {const t:Tabuleiro=Array.from({length:8},()=>Array(8).fill(null));const r:TipoPeca[]=['torre','cavalo','bispo','rainha','rei','bispo','cavalo','torre'];for(let i=0;i<8;i++){t[0][i]=criarPeca(r[i],'preto');t[1][i]=criarPeca('peao','preto');t[6][i]=criarPeca('peao','branco');t[7][i]=criarPeca(r[i],'branco');}return t;}
const igual=(a:Casa,b:Casa)=>a.linha===b.linha&&a.coluna===b.coluna; function caminhoLivre(a:Casa,b:Casa,t:Tabuleiro){const dl=Math.sign(b.linha-a.linha),dc=Math.sign(b.coluna-a.coluna);for(let l=a.linha+dl,c=a.coluna+dc;l!==b.linha||c!==b.coluna;l+=dl,c+=dc)if(t[l][c])return false;return true;}
export function localizarRei(cor:Cor,t:Tabuleiro):Casa|null{for(let l=0;l<8;l++)for(let c=0;c<8;c++)if(t[l][c]?.tipo==='rei'&&t[l][c]?.cor===cor)return{linha:l,coluna:c};return null;}
function ataca(o:Casa,d:Casa,t:Tabuleiro){const p=t[o.linha][o.coluna];if(!p)return false;const dx=Math.abs(d.coluna-o.coluna),dy=Math.abs(d.linha-o.linha),dl=d.linha-o.linha;if(p.modificadores.includes('salto_cavaleiro')&&((dx===2&&dy===1)||(dx===1&&dy===2)))return true;if(p.tipo==='peao')return dx===1&&dl===(p.cor==='branco'?-1:1);if(p.tipo==='cavalo')return(dx===2&&dy===1)||(dx===1&&dy===2);if(p.tipo==='rei')return dx<=1&&dy<=1;if(p.tipo==='torre')return(dx===0||dy===0)&&caminhoLivre(o,d,t);if(p.tipo==='bispo')return dx===dy&&caminhoLivre(o,d,t);return(dx===0||dy===0||dx===dy)&&caminhoLivre(o,d,t);}
export function casaAtacada(casa:Casa,por:Cor,t:Tabuleiro){for(let l=0;l<8;l++)for(let c=0;c<8;c++)if(t[l][c]?.cor===por&&ataca({linha:l,coluna:c},casa,t))return true;return false;} export const estaEmXeque=(cor:Cor,t:Tabuleiro)=>{const rei=localizarRei(cor,t);return rei?casaAtacada(rei,oposta(cor),t):true;};
export interface ContextoMovimento{direitosRoque?:Record<Cor,DireitosRoque>;enPassant?:Casa|null;}
function roqueValido(a:Casa,b:Casa,cor:Cor,t:Tabuleiro,d?:Record<Cor,DireitosRoque>){const home=cor==='branco'?7:0,curto=b.coluna===6,rights=d?.[cor];if(a.linha!==home||a.coluna!==4||b.linha!==home||!(curto?rights?.curto:rights?.longo))return false;const rook=t[home][curto?7:0];if(!rook||rook.tipo!=='torre'||rook.cor!==cor)return false;const between=curto?[5,6]:[1,2,3];if(between.some(c=>t[home][c]))return false;const enemy=oposta(cor);return !casaAtacada({linha:home,coluna:4},enemy,t)&&!casaAtacada({linha:home,coluna:curto?5:3},enemy,t)&&!casaAtacada(b,enemy,t);}
function pseudo(o:Casa,d:Casa,t:Tabuleiro,ctx:ContextoMovimento={}){if(!casaValida(o)||!casaValida(d)||igual(o,d))return false;const p=t[o.linha][o.coluna],alvo=t[d.linha][d.coluna];if(!p||alvo?.cor===p.cor||alvo?.tipo==='rei')return false;const dx=Math.abs(d.coluna-o.coluna),dy=Math.abs(d.linha-o.linha),dl=d.linha-o.linha,dir=p.cor==='branco'?-1:1,initial=p.cor==='branco'?6:1;if(p.modificadores.includes('salto_cavaleiro')&&((dx===2&&dy===1)||(dx===1&&dy===2)))return true;if(p.tipo==='peao'){if(p.modificadores.includes('marcha_lateral')&&dl===0&&dx===1&&!alvo)return true;if(dx===0&&dl===dir&&!alvo)return true;if(dx===0&&o.linha===initial&&dl===2*dir&&!alvo&&!t[o.linha+dir][o.coluna])return true;if(dx===1&&dl===dir&&!!alvo)return true;return dx===1&&dl===dir&&!alvo&&!!ctx.enPassant&&igual(d,ctx.enPassant);}if(p.tipo==='cavalo')return(dx===2&&dy===1)||(dx===1&&dy===2);if(p.tipo==='rei')return(dx<=1&&dy<=1)||(dy===0&&dx===2&&roqueValido(o,d,p.cor,t,ctx.direitosRoque));if(p.tipo==='torre')return(dx===0||dy===0)&&caminhoLivre(o,d,t);if(p.tipo==='bispo')return dx===dy&&caminhoLivre(o,d,t);return(dx===0||dy===0||dx===dy)&&caminhoLivre(o,d,t);}
export function aplicarNoTabuleiro(t:Tabuleiro,o:Casa,d:Casa,ctx:ContextoMovimento={}){const out=copiarTabuleiro(t),p=out[o.linha][o.coluna]!;out[o.linha][o.coluna]=null;if(p.tipo==='peao'&&ctx.enPassant&&igual(d,ctx.enPassant)&&!out[d.linha][d.coluna])out[o.linha][d.coluna]=null;out[d.linha][d.coluna]=p;if(p.tipo==='rei'&&Math.abs(d.coluna-o.coluna)===2){const from=d.coluna===6?7:0,to=d.coluna===6?5:3;out[d.linha][to]=out[d.linha][from];out[d.linha][from]=null;}return out;}
export const validarMovimento=(o:Casa,d:Casa,t:Tabuleiro,ctx:ContextoMovimento={})=>pseudo(o,d,t,ctx);
export function movimentosLegais(o:Casa,cor:Cor,t:Tabuleiro,ctx:ContextoMovimento={}):Casa[]{const p=t[o.linha]?.[o.coluna];if(!p||p.cor!==cor)return[];const r:Casa[]=[];for(let l=0;l<8;l++)for(let c=0;c<8;c++){const d={linha:l,coluna:c};if(pseudo(o,d,t,ctx)&&!estaEmXeque(cor,aplicarNoTabuleiro(t,o,d,ctx)))r.push(d);}return r;} export const movimentosValidos=(o:Casa,t:Tabuleiro)=>{const p=t[o.linha]?.[o.coluna];return p?movimentosLegais(o,p.cor,t):[];};
