import type { Carta, CartaId, Casa, Cor, Peca, Sala } from '../game/types.js';
export const LIMITE_MAO=3, LIMITE_CARTAS_POR_JOGO=3;
export const DEFINICOES_CARTAS: Record<CartaId,Carta>={ marcha_lateral:{id:'marcha_lateral',nome:'Marcha Lateral',descricao:'Concede a um peão a habilidade de mover 1 casa na horizontal até ele usar o movimento.'}, salto_cavaleiro:{id:'salto_cavaleiro',nome:'Salto do Cavalo',descricao:'Concede a qualquer peça um salto em L como o cavalo.'}, reviver_aliado:{id:'reviver_aliado',nome:'Reviver Aliado',descricao:'Permite que um bispo reviva uma peça capturada em uma casa vazia adjacente, sacrificando o próprio bispo.'} };
const base: CartaId[]=['marcha_lateral','marcha_lateral','marcha_lateral','salto_cavaleiro','salto_cavaleiro','reviver_aliado'];
export function criarBaralho(random=Math.random): CartaId[] { const pool=[...base],out:CartaId[]=[]; while(out.length<LIMITE_CARTAS_POR_JOGO&&pool.length){const i=Math.floor(random()*pool.length);out.push(pool.splice(i,1)[0]);} return out.sort(()=>random()-.5); }
export function normalizarCartas(dados: Partial<{mao:(Carta|CartaId)[];baralho:CartaId[]}>={}) { const out:CartaId[]=[]; for(const x of [...(dados.mao??[]),...(dados.baralho??[])]) { const id=typeof x==='string'?x:x.id; if(DEFINICOES_CARTAS[id]&&out.length<3&&!(id==='reviver_aliado'&&out.includes(id))) out.push(id); } while(out.length<3) { const x=criarBaralho().find(id=>id!=='reviver_aliado'||!out.includes(id)); if(!x) break; out.push(x); } return {mao:out.slice(0,3).map(id=>({...DEFINICOES_CARTAS[id]})),baralho:out.slice(3)}; }
export const adjacente=(a:Casa,b:Casa)=>Math.abs(a.linha-b.linha)<=1&&Math.abs(a.coluna-b.coluna)<=1&&(a.linha!==b.linha||a.coluna!==b.coluna);
export function movimentosRevive(sala:Sala,origem:Casa):Casa[] { const p=sala.tabuleiro[origem.linha]?.[origem.coluna]; if(!p||p.tipo!=='bispo'||!sala.jogadores[p.cor].cemiterio.length)return []; const out:Casa[]=[];for(let l=origem.linha-1;l<=origem.linha+1;l++)for(let c=origem.coluna-1;c<=origem.coluna+1;c++)if(l>=0&&l<8&&c>=0&&c<8&&adjacente(origem,{linha:l,coluna:c})&&!sala.tabuleiro[l][c])out.push({linha:l,coluna:c}); return out; }
export function aplicarCarta(sala:Sala,cor:Cor,dados:{cartaId:CartaId;origem:Casa;destino?:Casa;indiceRevivido?:number}):boolean { const j=sala.jogadores[cor],index=j.mao.findIndex(c=>c.id===dados.cartaId),p=sala.tabuleiro[dados.origem?.linha]?.[dados.origem?.coluna];if(cor!==sala.turno||j.cartaUsadaNesteTurno||index<0||!p||p.cor!==cor)return false; if(dados.cartaId==='marcha_lateral'){if(p.tipo!=='peao')return false;if(!p.modificadores.includes('marcha_lateral'))p.modificadores.push('marcha_lateral');}else if(dados.cartaId==='salto_cavaleiro'){if(!p.modificadores.includes('salto_cavaleiro'))p.modificadores.push('salto_cavaleiro');}else {if(p.tipo!=='bispo'||!dados.destino||!adjacente(dados.origem,dados.destino)||sala.tabuleiro[dados.destino.linha]?.[dados.destino.coluna])return false;const k=dados.indiceRevivido??j.cemiterio.length-1;if(!Number.isInteger(k)||k<0||k>=j.cemiterio.length)return false;const [rev]=j.cemiterio.splice(k,1);sala.tabuleiro[dados.origem.linha][dados.origem.coluna]=null;j.cemiterio.push({tipo:'bispo',cor,modificadores:[]});sala.tabuleiro[dados.destino.linha][dados.destino.coluna]={tipo:rev.tipo,cor:rev.cor,modificadores:[]};}j.mao.splice(index,1);j.cartaUsadaNesteTurno=true;return true; }
